### ISSUE TITLE
Créer des tables necessaire

### ISSUE THREAD

**Issue by Chenruii** [Chenruii/BeneVoisin#4]

**Comment by jhilzheber** [comment]
### TABLES EXISTANTES ###

- Adress
- DatePost
- Media
- Post
- PostType
- Theme
- User

### SUGGESTIONS DE TABLES ###

- A voir au fur et à mesure si des besoins se font sentir

**Comment by Chenruii** [comment]
-  Place-event
-  Post
-  Theme
-  User
- Residence
